pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url 'https://mobile-sdk.idwise.ai/releases/'
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://mobile-sdk.idwise.ai/releases/'
        }
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "IDWiseSimpleJourney"
include ':app'
